---

# Gerenciamnto de pacotes e atualização do SO

- name: Atualização do SO
  yum: name=* state=latest update_cache=yes

- name: Instalação de pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - net-tools
      - vim
      - nmap  

# configuração de Timezone
- name: Configurando Timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes           

...
