---

- name: Install Tools LPIC-2 Exam - 201 Packages on Debian
  apt:
     name: "{{item}}" 
     state: present
  loop: "{{debian_packages}}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install epel-repository
  yum: name=epel-release state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install Tools LPIC-2 Exam - 201 Packages on RedHat
  yum:
     name: "{{item}}" 
     state: present
  loop: "{{redhat_packages}}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install Tools LPIC-2 Exam - 201 Packages on OpenSuse System - Leap
  zypper:
     name: "{{item}}" 
     state: present
  loop: "{{opensuse_packages}}"
  when: ansible_distribution == 'openSUSE Leap' or ansible_distribution == 'SLES'
...

